name: Build and push release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The package release version
        required: true
        default: 1.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: install buildtools
        run: python3 -m pip install --upgrade pip build
        
      - name: build
        run: python3 -m build
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist/
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
